/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_soii;

import java.awt.Color;
import java.util.LinkedList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcosB
 */
public class Alocar extends javax.swing.JFrame {

    /**
     * Creates new form Alocar
     */
    public Alocar() {
        getContentPane().setBackground(Color.DARK_GRAY);
        initComponents();

        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox1.removeAllItems();

        jComboBox1.addItem("Exemplo 1");
        jComboBox1.addItem("Exemplo 2");
        jComboBox1.addItem("Exemplo 3");
        jComboBox1.addItem("Exemplo 4");
        jComboBox1.addItem("Exemplo 5");
        jComboBox1.addItem("Exemplo 6");
        jComboBox1.addItem("Exemplo 7");
        jComboBox1.addItem("Exemplo 8");
        jComboBox1.addItem("Exemplo 9");
        jComboBox1.addItem("Exemplo 10");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estratégias");
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alocar exemplo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("First-fit");

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Best-fit");

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Worst-fit");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGLA:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TAMANHO:");

        jTextField2.setText("0");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Alocar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //ISSO IRÁ ALOCAR ALGUNS PROGRAMAS E DESALOCAR, ASSIM TER IDEIA DE QUAL ESTRATÉGIA SE SAIU MELHOR

        if (jRadioButton1.isSelected()) {
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 1") {
                Exemplos.Exemplos1();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 2") {
                Exemplos.Exemplos2();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 3") {
                Exemplos.Exemplos3();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 4") {
                Exemplos.Exemplos4();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 5") {
                Exemplos.Exemplos5();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 6") {
                Exemplos.Exemplos6();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 7") {
                Exemplos.Exemplos7();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 8") {
                Exemplos.Exemplos8();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                }
                Trabalho_SOII.desalocar("B");
                Trabalho_SOII.desalocar("D");
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 9") {
                Exemplos.Exemplos9();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 10") {
                Exemplos.Exemplos10();
                Random gerador = new Random();
                LinkedList<Integer> salva = new LinkedList<>();
                salva.clear();
                int a;
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    while(salva.contains(a) == true){
                        a = gerador.nextInt(Exemplos.exemplos.size());
                    }
                    salva.add(a);
                    Trabalho_SOII.first_fit(Exemplos.exemplos.get(a));
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    Trabalho_SOII.desalocar(Exemplos.exemplos.get(a).getNome());
                }
            }
        } else if (jRadioButton2.isSelected()) {
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 1") {
                Exemplos.Exemplos1();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 2") {
                Exemplos.Exemplos2();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 3") {
                Exemplos.Exemplos3();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 4") {
                Exemplos.Exemplos4();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 5") {
                Exemplos.Exemplos5();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 6") {
                Exemplos.Exemplos6();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 7") {
                Exemplos.Exemplos7();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 8") {
                Exemplos.Exemplos8();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                 }
                Trabalho_SOII.desalocar("B");
                Trabalho_SOII.desalocar("D");
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 9") {
                Exemplos.Exemplos9();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 10") {
               Exemplos.Exemplos10();
                Random gerador = new Random();
                LinkedList<Integer> salva = new LinkedList<>();
                salva.clear();
                int a;
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    while(salva.contains(a) == true){
                        a = gerador.nextInt(Exemplos.exemplos.size());
                    }
                    salva.add(a);
                    Trabalho_SOII.best_fit(Exemplos.exemplos.get(a));
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    Trabalho_SOII.desalocar(Exemplos.exemplos.get(a).getNome());
                }
            }

        } else if (jRadioButton3.isSelected()) {
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 1") {
                Exemplos.Exemplos1();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 2") {
                Exemplos.Exemplos2();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 3") {
                Exemplos.Exemplos3();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 4") {
                Exemplos.Exemplos4();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 5") {
                Exemplos.Exemplos5();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 6") {
                Exemplos.Exemplos6();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 7") {
                Exemplos.Exemplos7();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 8") {
                Exemplos.Exemplos8();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                }
                Trabalho_SOII.desalocar("B");
                Trabalho_SOII.desalocar("D");
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 9") {
                Exemplos.Exemplos9();
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(i));
                    if (i == 2 || i == 5 || i == 10 || i == 14 || i == 18 || i == 23) {
                        Trabalho_SOII.desalocar(Exemplos.exemplos.get(i - 1).getNome());
                    }
                }
            }
            if (jComboBox1.getSelectedItem().toString() == "Exemplo 10") {
                Exemplos.Exemplos10();
                Random gerador = new Random();
                LinkedList<Integer> salva = new LinkedList<>();
                salva.clear();
                int a;
                for (int i = 0; i < Exemplos.exemplos.size(); i++) {
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    while(salva.contains(a) == true){
                        a = gerador.nextInt(Exemplos.exemplos.size());
                    }
                    salva.add(a);
                    Trabalho_SOII.worst_fit(Exemplos.exemplos.get(a));
                    a = gerador.nextInt(Exemplos.exemplos.size());
                    Trabalho_SOII.desalocar(Exemplos.exemplos.get(a).getNome());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um tipo de alocação");
        }
        Trabalho_SOII.Atualizar();
        Estrategias_alocacao.PA.setText("Total PA: "+Trabalho_SOII.lista.TotalProgramasAlocados());
        Estrategias_alocacao.inf.setText("Quantidade EL: "+Trabalho_SOII.lista.QuantidadeEspaçosVazios());
        Estrategias_alocacao.tam.setText("Tamanho EL: "+Trabalho_SOII.lista.TamanhoEspaçosVazios());
        Estrategias_alocacao.total.setText("Total EL: "+Trabalho_SOII.lista.TotalTamanhoEspaçosVazios());
        System.out.println("repintada");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jRadioButton1.isSelected()) {
            Trabalho_SOII.first_fit(new Programa(Integer.parseInt(jTextField2.getText()), jTextField1.getText(), true));
        } else if (jRadioButton2.isSelected()) {
            Trabalho_SOII.best_fit(new Programa(Integer.parseInt(jTextField2.getText()), jTextField1.getText(), true));

        } else if (jRadioButton3.isSelected()) {
            Trabalho_SOII.worst_fit(new Programa(Integer.parseInt(jTextField2.getText()), jTextField1.getText(), true));
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um tipo de alocação");
        }
        Trabalho_SOII.Atualizar();
        Estrategias_alocacao.PA.setText("Total PA: "+Trabalho_SOII.lista.TotalProgramasAlocados());
        Estrategias_alocacao.inf.setText("Quantidade EL: "+Trabalho_SOII.lista.QuantidadeEspaçosVazios());
        Estrategias_alocacao.tam.setText("Tamanho EL: "+Trabalho_SOII.lista.TamanhoEspaçosVazios());
        Estrategias_alocacao.total.setText("Total EL: "+Trabalho_SOII.lista.TotalTamanhoEspaçosVazios());
        System.out.println("repintada");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alocar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
